Nbis
SGBC/course pull request #15
Opened 2018-03-05 15:13 UTC by Juke34

Fix path to the correct lecture slides.
+ some typo correction

2018-03-06 07:35 UTC, HadrienG requested changes

2018-03-06 07:35 UTC, HadrienG commented on docs/nbis_annotation/schedule.md
> +**10.00-12.00** [Practical 3: Manual curation(incl. coffee break)](practical_session/ExerciseManCuration)
look at your file names. this change breaks the link

2018-03-06 07:35 UTC, HadrienG commented on docs/nbis_annotation/schedule.md
> +**13.00-15.30** [Practical 4: Functional annotation (incl. coffee break)](practical_session/ExerciseFuncAnnotInterp)
breaks the link to

2018-03-06 07:37 UTC, HadrienG commented on docs/nbis_annotation/schedule.md
> +**13.00-15.30** [Practical 4: Functional annotation (incl. coffee break)](practical_session/ExerciseFuncAnnotInterp)
your tutorials are **not** named `ExerciseManCuration` and `ExerciseFuncAnnotInterp` but rather practical3_manualCuration.md` and `practical4_funcAnnotInterp.md`, respectively. Rename your files or change the schedule

2018-03-08 16:57 UTC, Juke34 commented
It should be fine now !

2018-03-08 18:11 UTC, HadrienG approved these changes

2018-03-08 18:12 UTC, merged